name: barbergo_flutter
description: Aplikasi BarberGo untuk tukang cukur

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.1.1
  file_picker: ^8.0.0+1  # atau versi terbaru
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.12
  permission_handler: ^11.0.1
  pusher_channels_flutter: ^2.0.0
  laravel_echo: 1.0.0-beta.1
  socket_io_client: ^2.0.3+1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true